import type { Metadata } from 'next';
import './globals.css';
import Provider from './lib/providers';
import { ColorModeScript } from '@chakra-ui/react';
export const metadata: Metadata = {
  title: 'Admin Dasboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <ColorModeScript initialColorMode='dark' />
      </head>
      <body>
        <Provider initialColorMode='dark'>{children}</Provider>
      </body>
    </html>
  );
}
