import type { Metadata } from 'next';
import './globals.css';
import NavContext from './context/ThemeContext';

export const metadata: Metadata = {
  title: 'Admin Dasboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NavContext>
      <html lang='en'>
        <body>{children}</body>
      </html>
    </NavContext>
  );
}
